version: '2'
services:
  mirkotfg-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/mirkotfg/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mirkotfg
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
